apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-template-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asp-template
  template:
    metadata:
      labels:
        app: asp-template
    spec:
      imagePullSecrets:
      - name: local-registry-secret
      containers:
      - name: asp-template-container
        image: utility.ndkn.local/ndkn/asp-template
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"